# Generated by Django 5.1 on 2024-08-31 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_created_by_alter_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='event',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='available_slots',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='skills_needed',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_volunteers',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('interested_fields', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.userprofile'),
        ),
        migrations.DeleteModel(
            name='ExtendUser',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.AddField(
            model_name='event',
            name='fields',
            field=models.TextField(default='na'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
