# Generated by Django 5.1 on 2024-09-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interested_fields',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='event',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.field'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills_needed',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_fields',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='api.field'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='api.skill'),
        ),
    ]
