# Generated by Django 5.1 on 2024-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_field_skill_remove_event_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(default=list, related_name='participants', to='api.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fields',
            field=models.ManyToManyField(default=list, related_name='events', to='api.field'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skills_needed',
            field=models.ManyToManyField(default=list, related_name='events', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_fields',
            field=models.ManyToManyField(default=list, related_name='user_profile', to='api.field'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(default=list, related_name='user_profile', to='api.skill'),
        ),
    ]
