# Generated by Django 5.1 on 2024-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_event_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
