# Generated by Django 5.1 on 2024-09-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_event_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
    ]
