# Generated by Django 5.1 on 2024-10-01 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='api.event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='api.skill'),
        ),
    ]
