# Generated by Django 5.1 on 2024-10-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
