# Generated by Django 5.1 on 2024-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_notification_user_id_alter_notification_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matched_events',
            field=models.ManyToManyField(blank=True, related_name='matched_users', to='api.event'),
        ),
    ]
